chains:
  celo:
    name: Celo
    chain_id: 42220
    enabled: true
    bridge_verified: true
    quote_tier: onchain
    hub_stable: USDT
    hub_token: "0x48065fbbe25f71c9282ddf5e1cd6d6a887483d5e"
    hub_decimals: 6
    rpc_env: RPC_CELO
    swap_router: "0x5615CDAb10dc425a742d643d949a7F474C01abc4"
    quoter_v2: "0x82825d0554fA07f7FC52Ab63c961F330fdEFa8E8"
    pools:
      vchf_usdt:
        address: "0x899f68521196b4db5e3525e8ce1695efa9b05533"
        fee: 100
        token0_is_vchf: true

  solana:
    name: Solana
    chain_type: solana
    chain_id: 0
    enabled: true
    bridge_verified: true
    quote_tier: jupiter
    hub_stable: USDC
    hub_token: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
    hub_decimals: 6
    rpc_env: RPC_SOLANA

  vnx:
    name: VNX Platform
    chain_type: vnx
    chain_id: 0
    enabled: true
    bridge_verified: true
    quote_tier: vnx
    hub_stable: USDC
    hub_token: USDC
    hub_decimals: 6
    rpc_env: VNX_API_PUBLIC_KEY

  ethereum:
    name: Ethereum
    chain_id: 1
    enabled: true
    bridge_verified: true
    quote_tier: onchain
    hub_stable: USDC
    hub_token: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    hub_decimals: 6
    rpc_env: RPC_ETHEREUM
    swap_router: "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45"
    quoter_v2: "0x61FFECFE9BB63D7D8Bf820cDf982491D0Aa54881"
    pools:
      usdt_usdc:
        address: "0x3416cF6C708Da44DB2624D63ea0AAef7113527C6"
        fee: 100
        token0_is_usdt: true
