tokens:
  VCHF:
    symbol: VCHF
    decimals: 18
    chain_decimals:
      solana: 9
    chains:
      base: "0x1fca74d9ef54a6ac80ffe7d3b14e76c4330fd5d8"
      solana: "AhhdRu5YZdjVkKR3wbnUDaymVQL2ucjMQ63sZ3LFHsch"
      vnx: VCHF
